### PR TITLE
improve http support

### PR DESCRIPTION
**Pull request by aoleg94**
1. allow custom http port
2. allow darkhttpd and `python -m http.server` as servers, not only apache httpd

### CODE REVIEW

**Comment by darkxex** [comment]
@proconsule could you test this, please?

**Comment by proconsule** [comment]
i will check it soon

**Comment by darkxex** [comment]
> i will check it soon

Once you review it, I'll post it as Nightly 7

**Comment by proconsule** [comment]
> > i will check it soon
> 
> Once you review it, I'll post it as Nightly 7

I tested it and is working

**Comment by darkxex** [comment]
> > > i will check it soon
> > 
> > Once you review it, I'll post it as Nightly 7
> 
> I tested it and is working

OK, I will merge this, and tomorrow I will update the Nightly.

**Comment by Mymax74** [comment]
hi,where i can found a video tutorial how set my decoder zgemma with nintendo switch and the app nxmp..i dont undestand what i do for setting…thanks

**Pull request merged**
